# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~


    encoders:
        alkani\PSIBundle\Entity\User: bcrypt


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
 #       dev:
  #          pattern: ^/(_(profiler|wdt)|css|images|js)/
   #         security: false

        secured_area:

            pattern: ^/
            form_login:
                login_path: login
                check_path: login_check
                target_path_parameter: login_success

            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
